from enum import Enum


class ResultTypeEnum(Enum):
    SHOW_ALL = "SHOW_ALL"
    SHOW_LAST_EXECUTION_RESULT = "SHOW_LAST_EXECUTION_RESULT"
    SHOW_HAS_PASSED_ONLY = "SHOW_HAS_PASSED_ONLY"


class ExecutionTestResultEnum(Enum):
    PASSED = "PASSED"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    WRONG_ANSWER = "WRONG_ANSWER"
    PRESENTATION_ERROR = "PRESENTATION_ERROR"
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED"
    MEMORY_LIMIT_EXCEEDED = "MEMORY_LIMIT_EXCEEDED"
    SECURITY_VIOLATION = "SECURITY_VIOLATION"
    COMPILATION_ERROR = "COMPILATION_ERROR"
